# -*- mode: python ; coding: utf-8 -*-
"""PyInstaller spec for 评论抓取工具."""

import os
from pathlib import Path

a = Analysis(
    ['main.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('config.ini.example', '.'),
        ('input', 'input'),
    ],
    hiddenimports=[
        'classifier',
        'config',
        'video_processor',
        'scrapers',
        'scrapers.base',
        'scrapers.douyin',
        'scrapers.xiaohongshu',
        'scrapers.weibo',
        'scrapers.wechat',
        'scrapers.wechat_official',
        'scrapers.wechat_channels',
        'scrapers.wechat_channels_emulator',
        'scrapers.appium_base',
        'scrapers.toutiao',
        'scrapers.comment_cleaner',
        'playwright',
        'playwright.async_api',
        'playwright.sync_api',
        'playwright._impl',
        'playwright._impl._browser_type',
        'playwright._impl._browser_context',
        'playwright._impl._page',
        'openpyxl',
        'requests',
        'pyautogui',
        'rapidocr_onnxruntime',
        'onnxruntime',
        'numpy',
        'asyncio',
        'json',
        'urllib.parse',
        'httpx',
        'imageio_ffmpeg',
        'imageio',
        'hashlib',
        'base64',
        'pathlib',
        'logging',
        'os',
        'sys',
        'platform',
        're',
        'subprocess',
        'concurrent.futures',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=['pytest', 'mitmproxy', 'pywinauto'],
    noarchive=False,
)

pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='评论抓取工具',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    icon=None,
)
